version: '3.8'
services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    networks:
      - lambda-local
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8000:8000"
    working_dir: /home/dynamodblocal

networks:
  lambda-local:
    external: true
