AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  terraform-aws-ecs-tagdb

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    LoggingConfig:
      LogFormat: JSON

Resources:
  TagDBFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/tagdb.handler
      Runtime: python3.9
      Architectures:
      - x86_64
